name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  example:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Setup Secrets.swift
        run: cp Examples/Examples/_Secrets.swift Examples/Examples/Secrets.swift
      - name: Build example
        run: make build-example

  test-library:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Setup Secrets.swift
        run: cp Examples/Examples/_Secrets.swift Examples/Examples/Secrets.swift
      - name: Test library
        run: make test-library
    
